# Generated by Django 4.0.3 on 2022-03-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
