# Generated by Django 4.0.3 on 2022-03-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddies', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
