# Generated by Django 4.0.3 on 2022-04-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddies', '0006_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='bookBuy1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
