# Generated by Django 4.0.3 on 2022-04-24 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddies', '0009_remove_exchange_bookbuy1_exchange_bookbuy1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='username',
            field=models.CharField(blank=True, default=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL), max_length=255),
        ),
    ]
