# Generated by Django 4.0.3 on 2022-04-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddies', '0011_alter_exchange_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='bookBuy1',
        ),
        migrations.AddField(
            model_name='exchange',
            name='bookBuy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookBuy1', to='bookbuddies.book'),
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='bookBuy2',
        ),
        migrations.AddField(
            model_name='exchange',
            name='bookBuy2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookBuy2', to='bookbuddies.book'),
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='bookBuy3',
        ),
        migrations.AddField(
            model_name='exchange',
            name='bookBuy3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookBuy3', to='bookbuddies.book'),
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='bookSell',
        ),
        migrations.AddField(
            model_name='exchange',
            name='bookSell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookSell', to='bookbuddies.book'),
        ),
    ]
