# Generated by Django 4.0.3 on 2022-05-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddies', '0013_remove_exchange_user_exchange_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='isSettled',
            field=models.BooleanField(default=False),
        ),
    ]
